apiVersion: apps/v1
kind: Deployment
metadata:
  name: invest-dairy
spec:
  replicas: 1
  selector:
      matchLabels:
        app: invest-dairy
  template:
    metadata:
      labels:
        app: invest-dairy
    spec:
      containers:
        - name: invest-dairy
          image: registry.ap-south-1.aliyuncs.com/indiarupeeloan/great/invest-dairy:0.0.1
          ports:
          - containerPort: 80
          - containerPort: 3001
          env:
          - name: GOROOT
            value: /usr/local/go
          - name: GOPATH
            value: /go
      imagePullSecrets:
        - name: syl-docker-secret
